# Generated by Django 4.0.6 on 2022-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
