# Generated by Django 4.0.6 on 2022-08-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0003_color_type_transaction_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('code', models.ImageField(blank=True, upload_to='code')),
            ],
        ),
    ]
