# Generated by Django 4.0.6 on 2022-08-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0004_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wemes.qrcode'),
        ),
    ]
